// <auto-generated />
namespace MVCAppCodeFirstMigrationExample.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class Update01 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Update01));
        
        string IMigrationMetadata.Id
        {
            get { return "202505040814013_Update-01"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
