// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SudApi.Models;

#nullable disable

namespace SudApi.Migrations
{
    [DbContext(typeof(MvcDbContext))]
    [Migration("20250907072431_Creating-FarmersDB")]
    partial class CreatingFarmersDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SudApi.Models.Farmer", b =>
                {
                    b.Property<int>("Custid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Custid"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("FB_Pieces")
                        .HasColumnType("float");

                    b.Property<double>("FB_Price")
                        .HasColumnType("float");

                    b.Property<string>("FirstBreed")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("Varchar");

                    b.Property<double?>("SB_Pieces")
                        .HasColumnType("float");

                    b.Property<double?>("SB_Price")
                        .HasColumnType("float");

                    b.Property<string>("SecondBreed")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("TB_Pieces")
                        .HasColumnType("float");

                    b.Property<double?>("TB_Price")
                        .HasColumnType("float");

                    b.Property<string>("ThirdBreed")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Custid");

                    b.ToTable("Farmers");
                });
#pragma warning restore 612, 618
        }
    }
}
