// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SudApi.Models;

#nullable disable

namespace SudApi.Migrations
{
    [DbContext(typeof(MvcDbContext))]
    [Migration("20250807070238_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SudApi.Models.Category", b =>
                {
                    b.Property<int>("C_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("C_Id"));

                    b.Property<string>("C_Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("C_Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            C_Id = 1,
                            C_Description = "Monitors, Laptops",
                            C_Name = "Hardware"
                        },
                        new
                        {
                            C_Id = 2,
                            C_Description = "Eye lashes, Mascara etc",
                            C_Name = "Beauty"
                        },
                        new
                        {
                            C_Id = 3,
                            C_Description = "Brush, Paste etc",
                            C_Name = "Household"
                        });
                });

            modelBuilder.Entity("SudApi.Models.Product", b =>
                {
                    b.Property<int>("P_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("P_Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("P_Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("P_Price")
                        .HasColumnType("float");

                    b.HasKey("P_Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            P_Id = 101,
                            CategoryId = 1,
                            P_Description = "Computer Monitor",
                            P_Name = "Monitor",
                            P_Price = 250.5
                        },
                        new
                        {
                            P_Id = 102,
                            CategoryId = 3,
                            P_Description = "Household",
                            P_Name = "Brush",
                            P_Price = 260.5
                        },
                        new
                        {
                            P_Id = 103,
                            CategoryId = 2,
                            P_Description = "Beauty",
                            P_Name = "Mascara",
                            P_Price = 270.5
                        },
                        new
                        {
                            P_Id = 104,
                            CategoryId = 3,
                            P_Description = "Household",
                            P_Name = "Paste",
                            P_Price = 280.5
                        },
                        new
                        {
                            P_Id = 105,
                            CategoryId = 2,
                            P_Description = "Beauty",
                            P_Name = "Eye Lashes",
                            P_Price = 290.5
                        },
                        new
                        {
                            P_Id = 106,
                            CategoryId = 1,
                            P_Description = "Computer Monitor",
                            P_Name = "Laptop",
                            P_Price = 300.5
                        },
                        new
                        {
                            P_Id = 107,
                            CategoryId = 2,
                            P_Description = "Beauty",
                            P_Name = "foundation",
                            P_Price = 350.5
                        },
                        new
                        {
                            P_Id = 108,
                            CategoryId = 3,
                            P_Description = "Household",
                            P_Name = "dustbin",
                            P_Price = 550.5
                        });
                });

            modelBuilder.Entity("SudApi.Models.Product", b =>
                {
                    b.HasOne("SudApi.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
