// <auto-generated />
using AspNetCoreMvc_FinalProject.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AspNetCoreMvc_FinalProject.Migrations
{
    [DbContext(typeof(MvcCoreDBContext))]
    [Migration("20250528075948_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AspNetCoreMvc_FinalProject.Models.Customer", b =>
                {
                    b.Property<int>("Custid")
                        .HasColumnType("int");

                    b.Property<decimal?>("Balance")
                        .HasColumnType("Money");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("Varchar");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("Varchar");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("Custid");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Custid = 101,
                            Balance = 25000.00m,
                            City = "Melbourne",
                            Name = "Sudheer",
                            Status = true
                        },
                        new
                        {
                            Custid = 102,
                            Balance = 26000.00m,
                            City = "Sydney",
                            Name = "Eswar",
                            Status = true
                        },
                        new
                        {
                            Custid = 103,
                            Balance = 27000.00m,
                            City = "Perth",
                            Name = "Siri",
                            Status = true
                        },
                        new
                        {
                            Custid = 104,
                            Balance = 28000.00m,
                            City = "Brisbane",
                            Name = "Srija",
                            Status = true
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
